apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlining-frontend
  # namespace: streaming 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: frontend-app
        tier: frontend
        track: stable
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend-app
          image: "core.harbor.domain/library/frontend-app"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "150Mi"
              cpu: "300m"
            requests:
              memory: "100Mi"
              cpu: "250m"
          volumeMounts:
                      #override config.js file
            - name: config
              mountPath: "/usr/share/nginx/html/config.js"
              subPath: "config.js"
      volumes:
          - name: config
            configMap:
              name: frontend-web-config
              items:
                  - key: "web.properties"
                    path: "config.js"
---

apiVersion: v1
kind: Service
metadata:
  name: streamlining-frontend-service
  # namespace: streaming 
spec:
  selector:
    app: frontend-app
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 80
    nodePort: 30003
  type: LoadBalancer


---
apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-web-config
    # namespace: streaming 
data:
    web.properties: |
        window.REACT_APP_Backend_URL = "http://103.153.118.69:30002/"
